# Site settings
title: bailey brooks
description: hi, i'm bailey
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "baibrooks.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: bailey brooks
user_description: 
user_title: product manager
email: bailey@github.com
twitter_username: __baileybrooks
github_username:  bailey

plugins:
  - jekyll-seo-tag

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
